from ABBusqueda import ABBusqueda
from ABNormal import  ABNormal
from Nodo import Nodo

print('==================Estructura de Arboles=========================')
print('========Se instancia un Arbol Binario Normal=========')
abn=ABNormal()
print('========Se llena con datos el arbol binario normal=========')
abn.llenar()
print('======Se muestra los datos por nivel=======')
abn.m_nivel()
print('======Se muestra los datos en orden=======')
abn.enorder(abn.getR())
print()
print('======Se muestra los datos en preorden=======')
abn.preorder(abn.getR())
print()
print('======Se muestra los datos en posorden=======')
abn.posorden(abn.getR())
print()
print('======Se muestra la Altura del Arbol=======')
print("la altura es: ",abn.alturaArbol())

print('========Se instancia un Arbol Binario Busqueda=========')
ab=ABBusqueda()
print('========Se llena con datos el arbol binario normal=========')
ab.llenar()
print('======Se muestra los datos por nivel=======')
ab.m_nivel()
print('======Se muestra los datos en orden=======')
ab.enorder(ab.getR())
print()
print('======Se muestra los datos en preorden=======')
ab.preorder(ab.getR())
print()
print('======Se muestra los datos en posorden=======')
ab.posorden(ab.getR())
print()
print('======Se muestra la Altura del Arbol=======')
print("la altura es: ",ab.alturaArbol())
print('======Insertar un nuevo elemnto=======')
d=int(input('Inserte un nuevo dato... '))
x=Nodo(d)
ab.insertar(x,ab.getR())
print(" Vista con el nuevo dato  ")
print()
ab.m_nivel()
print('======Nueva Altura del Arbol=======')
print("la altura es: ",ab.alturaArbol())